pymin/pymin/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from pymin import db, login
from flask_login import UserMixin


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    posts = db.relationship('Post', backref='author', lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Post {}>'.format(self.body)


@login.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

pymin/pymin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo
from pymin.models import User


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('Please use a different email address.')

pymin/pymin/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
app = Flask(__name__, instance_relative_config=True)


def create_app():
    app.config.from_object('config.DevConfig')

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    login.login_view = 'login'

    with app.app_context():
        from . import views, models
        app.register_blueprint(views.bp)

    @app.route('/hello')
    def hello():
        return "kurva anyadat"
    
    return app

pymin/pymin/views.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import logout_user
from pymin.services import Services

bp = Blueprint('views', __name__)
services = Services()


@bp.route('/')
def index():
    return render_template('index.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    services.check_if_authenticated()
    return services.handle_login()


@bp.route('/logout')
def logout():
    logout_user()
    flash('Successful logout.')
    return redirect(url_for('views.index'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    services.check_if_authenticated()
    return services.validate_form()

pymin/pymin/templates/index.html
{% extends 'layout.html' %}
{% block content %}
{% endblock %}

pymin/pymin/templates/layout.html
<!doctype html>
<html lang="en">
	<head>
		<title>kutyaszar</title>
		<meta charset="utf-8">
		<meta name="description" content={{description}}>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- Bootstrap CSS -->
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
		<!-- Bootstrap icon font szarsag -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
	</head>
	<body style="padding: 70px">
		{% include 'nav.html' %}
		{% include 'messages.html' %}
		<main role="main" class="container">
			<div class="d-flex justify-content-center">
				{% block content %}{% endblock %}
			</div>
		</main>
		<!-- Bootstrap Bundle with Popper -->
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
	</body>
</html>

pymin/pymin/templates/login.html
{% extends "layout.html" %}

{% block content %}
<form class="form-signin" action="" method="post" novalidate>
    <div class="form-floating mb-3">
        <input type="text" class="form-control" name="username" id="floatingInput" placeholder="Lakatos">
        <label for="floatingInput">Username</label>
    </div>
    <div class="form-floating">
        <input type="password" class="form-control" name="pw" id="floatingPassword" placeholder="Password">
        <label for="floatingPassword">Password</label>
    </div>
    <div class="checkboc mb-3">
        <label>
            <input type="checkbox" name="remember" value="remember-me"> Remember me
        </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
</form>
{% endblock %}

pymin/pymin/templates/messages.html
{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="container">
{% for message in messages %}
	<div class="alert alert-success">
{{ message }}
	</div>
{% endfor %}
</div>
{% endif %}
{% endwith %}

pymin/pymin/templates/nav.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
		<a href="#" class="navbar-brand">kutyaszar</a>
		<button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<div class="navbar-nav ms-auto">
				{% if current_user.is_anonymous %}
				<a href="{{ url_for('views.login') }}" class="nav-item nav-link">Login</a>
				{% else %}
				<a class="nav-item nav-link">{{ current_user.username }}</a><a href="{{ url_for('views.logout') }}" class="nav-item nav-link">Logout</a>
				{% endif %}
			</div>
		</div>
	</div>
</nav>

pymin/pymin/templates/register.html
{% extends "layout.html" %}

{% block content %}
    <h1>Register</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}<br>
            {% for error in form.username.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=64) }}<br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}<br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2(size=32) }}<br>
            {% for error in form.password2.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}